import os
import sys

# CONFIGURATION PATH INIT HTK-BOT
PATH_BINARY_FIREFOX = os.environ.get('PATH_BINARY_FIREFOX', 'NOT SET FIREFOX BINARY PATH')
SITE_EXAMPLE= os.environ.get('SITE_EXAMPLE', 'NOT SET SITE EXAMPLE BOT')
SETTINGS_PATHS_CONFIG_BOT = (
    PATH_BINARY_FIREFOX,
    SITE_EXAMPLE
)

#CONFIGURATION PATH OF DIR SAVE CSV DOWNLOAD BY BOT.
PATH_SAVE_CSV = os.environ.get('PATH_SAVE_CSV', 'NOT SET PATH SAVE CSV')
SETTINGS_PATH_SAVE_ARCH_CSV = (
    PATH_SAVE_CSV,

)




